M_18_Django_Cache/mysite/blogapp/urls.py
from django.urls import path

from .views import ArticleListView, ArticleCreateView


app_name = 'blogapp'


urlpatterns = [
    path("article/", ArticleListView.as_view(), name="article_list"),
    path("article/create/", ArticleCreateView.as_view(), name="create_article"),
    ]

M_18_Django_Cache/mysite/myauth/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView


from .views import \
    get_cookie_view, \
    set_cookie_view, \
    get_session_view, \
    set_session_view, \
    MyLogoutView, \
    RegisterView, \
    AboutMe, \
    AvatarUpdateView, \
    ProfileListView, \
    ProfileDetailsView, \
    ProfileRegisterView, \
    ProfileDeleteView, \
    update_profile

app_name = 'accounts'


urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("profiles/", ProfileListView.as_view(), name="profile_list"),
    path("profiles/create/", ProfileRegisterView.as_view(), name="profile_create"),
    path("profiles/<int:pk>/", ProfileDetailsView.as_view(), name="profile_detail"),
    path("about-me/", AboutMe.as_view(), name="about-me"),
    path("profiles/update_profile/", update_profile, name="profile_update"),
    path("profiles/avatar/<int:pk>/update/", AvatarUpdateView.as_view(), name="avatar_update"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/<int:pk>/delete/", ProfileDeleteView.as_view(), name="profile_delete"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
]

M_18_Django_Cache/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from django.conf.urls.i18n import i18n_patterns
from .sitemaps import sitemaps

urlpatterns = [
    # path('', include('shopapp.urls')),
    # path('shop/', include('shopapp.urls')),
    # path('admin/doc/', include('django.contrib.admindocs.url')),
    # path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('blogapp/', include('blogapp.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",)

]

urlpatterns += i18n_patterns(
    path('', include('shopapp.urls')),
    path('shop/', include('shopapp.urls')),
    path('api/schema', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

M_18_Django_Cache/mysite/blogapp/models.py
from django.db import models


class Author(models.Model):
    """
    Модель **Author** представляет автора статьи,
    который имеет поля: имя 'name' и биография 'bio'.
    """

    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=100, db_index=True)
    bio = models.TextField(null=False, blank=True)

    def __str__(self) -> str:
        return f"Author(pk={self.pk}, name={self.name!r})"


class Category(models.Model):
    """
    Модель **Category** представляет категорию статьи,
    который имеет поле: название категории 'name'.
    """

    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=40, db_index=True)

    def __str__(self) -> str:
        return f"Category(pk={self.pk}, name={self.name!r})"


class Tag(models.Model):
    """
    Модель **Tag** представляет тэг статьи,
    который можно назначить статьи и имеет поле: название тэга 'name'.
    """

    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=20, db_index=True)

    def __str__(self) -> str:
        return f"Tag(pk={self.pk}, name={self.name!r})"


class Article(models.Model):
    """
    Модель **Article** представляет статью,
    которая имеет поля:
        tittle - заголовок статьи
        content - содержимое статьи
        pub_date - дата публикации статьи
        author - автор статьи
        category - категория статьи
        tags - тэги статьи
    """

    class Meta:
        ordering = ['author', 'title']

    title = models.CharField(max_length=200, db_index=True)
    content = models.TextField(null=False, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

M_18_Django_Cache/mysite/blogapp/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from .models import Article


class ArticleListView(ListView):
    """Вывод списка статей."""

    queryset = (
        Article.objects.defer("content", "id").select_related("author", "category").prefetch_related("tags")
    )


class ArticleCreateView(CreateView):
    """Создание новой статьи."""

    model = Article
    fields = "title", "content", "author", "category", "tags"
    success_url = reverse_lazy("blogapp:article_list")

M_18_Django_Cache/mysite/blogapp/templates/blogapp/article_form.html
{% extends 'blogapp/base.html' %}

{% block title %}
    Create article
{% endblock %}

{% block body %}
    <h1>
        Create a new article
    </h1>

    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>
   <div>
        <a href="{% url 'blogapp:article_list' %}"> Article List</a>
    </div>
{% endblock %}

M_18_Django_Cache/mysite/blogapp/templates/blogapp/article_list.html
{% extends 'blogapp/base.html' %}

{% block title %}
    Articles List
{% endblock %}

{% block body %}
    <h1>
        Articles:
    </h1>
    {% if object_list %}
        <div>
            {% for article in object_list %}
                <div>
                    <p>Title: {{ article.title }}</p>
                    <p>Pub_Date: {{ article.pub_date }}</p>
                    <p>Author: {{ article.author.name }}</p>
                    <p>Category: {{ article.category.name }}</p>
                    <p>Tags:
                        <ul>
                            {% for tag in article.tags.all %}
                                <li>{{ tag.name }}</li>
                            {% endfor %}
                        </ul>
                    </p>
                    <br>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p> Not articles </p>
    {% endif %}
    <div>
        <a href="{% url 'blogapp:create_article' %}">Create article</a>
    </div>
{% endblock %}

M_18_Django_Cache/mysite/blogapp/templates/blogapp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base body
    {% endblock %}
<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today in {{ current_weekday }}
</div>
</body>
</html>