M_18_Django_Cache/mysite/myauth/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView


from .views import \
    get_cookie_view, \
    set_cookie_view, \
    get_session_view, \
    set_session_view, \
    MyLogoutView, \
    RegisterView, \
    AboutMe, \
    AvatarUpdateView, \
    ProfileListView, \
    ProfileDetailsView, \
    ProfileRegisterView, \
    ProfileDeleteView, \
    update_profile

app_name = 'accounts'


urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("profiles/", ProfileListView.as_view(), name="profile_list"),
    path("profiles/create/", ProfileRegisterView.as_view(), name="profile_create"),
    path("profiles/<int:pk>/", ProfileDetailsView.as_view(), name="profile_detail"),
    path("about-me/", AboutMe.as_view(), name="about-me"),
    path("profiles/update_profile/", update_profile, name="profile_update"),
    path("profiles/avatar/<int:pk>/update/", AvatarUpdateView.as_view(), name="avatar_update"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/<int:pk>/delete/", ProfileDeleteView.as_view(), name="profile_delete"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
]

M_18_Django_Cache/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from django.conf.urls.i18n import i18n_patterns
from .sitemaps import sitemaps

urlpatterns = [
    # path('', include('shopapp.urls')),
    # path('shop/', include('shopapp.urls')),
    # path('admin/doc/', include('django.contrib.admindocs.url')),
    # path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('blogapp/', include('blogapp.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",)

]

urlpatterns += i18n_patterns(
    path('', include('shopapp.urls')),
    path('shop/', include('shopapp.urls')),
    path('api/schema', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

M_18_Django_Cache/mysite/shopapp/urls.py
from django.urls import path, include


from rest_framework.routers import DefaultRouter

from .views import shop_index, \
    groups_list, \
    ProductsListView, \
    ProductsDetailsView, \
    ProductCreateView, \
    OrderCreateView, \
    ProductUpdateView, \
    ProductDeleteView, \
    OrderListView,\
    OrderDetailView,\
    OrderUpdateView,\
    OrderDeleteView, \
    OdersDataExportView, \
    ProductViewSet, \
    OrderViewSet, \
    LatestProductsFeed, \
    UserOrdersListView, \
    UserOrdersDataExportView

app_name = 'shopapp'

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)


urlpatterns = [
    path("", shop_index, name="index"),
    path("api/", include(routers.urls)),
    path("groups/", groups_list, name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="create_product"),
    path("products/latest/feed/", LatestProductsFeed(), name="products_feed"),
    path("products/<int:pk>/", ProductsDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archived/", ProductDeleteView.as_view(), name="product_archived"),
    path("order/", OrderListView.as_view(), name="order_list"),
    path("order/export/", OdersDataExportView.as_view(), name="export_orders"),
    path("order/create/", OrderCreateView.as_view(), name="create_order"),
    path("order/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("order/<int:pk>/update", OrderUpdateView.as_view(), name="order_update"),
    path("order/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders"),
    path("users/<int:user_id>/orders/export/", UserOrdersDataExportView.as_view(), name="export_user_orders"),


]

M_18_Django_Cache/mysite/shopapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core import validators
from django.urls import reverse
from PIL import Image
from django.utils.translation import gettext_lazy as _


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return f"product/product_{instance.pk}/image/{filename}"


class Product(models.Model):
    """
    Модель **Product** представляет товар,
    который можно продавать в магазине.

    Изображения товара тут: :model:`shopapp.ProductImage`

    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ["name", "price"]
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    name = models.CharField(max_length=100)
    description = models.TextField(
        null=False, blank=True,
        validators=[validators.RegexValidator(regex=r"Made in",
                                              message="The field must contain words 'Made in'")])
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.preview:
            img = Image.open(self.preview.path)
            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.preview.path)

    def get_absolute_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.pk})
    # @property
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + "..."

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"


def product_image_directory_path(instance: "ProductImage", filename: str) -> str:
    return f"product/product_{instance.product.pk}/image/{filename}"


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_image_directory_path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)
            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.image.path)


class Order(models.Model):
    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    delivery_address = models.TextField(
        null=False, blank=False,
        validators=[validators.RegexValidator(regex=r"city",
                                              message="The field must contain word 'city'")])
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")

M_18_Django_Cache/mysite/shopapp/forms.py
from django import forms
from .models import Product, Order


class ProductsForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount"


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "user", "delivery_address", "promocode", "products"


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

M_18_Django_Cache/mysite/shopapp/templates/shopapp/base.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base body
    {% endblock %}
<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today in {{ current_weekday }}
</div>
</body>
</html>

M_18_Django_Cache/mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups List
{% endblock %}

{% block body %}
    <h1>
        Groups:
    </h1>
    <div>
        {% if not groups%}
            <h3>
                No groups
            </h3>
        {% else %}
            <ul>
                {% for group in groups %}
                    <li>
                        <div>{{ group.name }}</div>
                        <ul>
                            {% for permission in group.permissions.all %}
                                <li>
                                    {{ permission.name }}
                                    (<code> {{ permission.codename }} </code>)
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Delete Order {{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete order {{ object.pk }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token%}
            {{ form.as_p}}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>
        Order # {{ object.pk }}
    </h1>
     <div>
         <p>Order by: {% firstof object.user.first_name object.user.username %}</p>
         <p>Delivery_address: {{ object.delivery_address }}</p>
         <p>Promocode: {{ object.promocode }}</p>
     </div>
        <div>
            Products in order
            <ul>
                {% for product in object.products.all %}
                <li> {{ product.name }} for $ {{ product.price }} </li>
                {% endfor %}
            </ul>
        </div>
    <div>
        <a href="{% url 'shopapp:order_update' pk=object.pk %}"> Update order </a>
    </div>
    <div>
        <a href=" {% url 'shopapp:order_delete' pk=object.pk %}">Delete order </a>
    </div>
    <div>
        <a href="{% url 'shopapp:order_list' %}"> Back to orders </a>
    </div>
{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>
        Create a new order
    </h1>

    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Create
            </button>
        </form>
    </div>
   <div>
        <a href="{% url 'shopapp:order_list' %}"> Order List</a>
    </div>
{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order List
{% endblock %}

{% block body %}
    <h1>
        Order:
    </h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
                <div>
                    <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Order # {{order.pk}}</a></p>
                    <p>Order by: {% firstof order.user.first_name order.user.username %}</p>
                </div>
                <div>
                    Products in order
                        <ul>
                            {% for product in order.products.all %}
                                <li> {{ product.name }} for $ {{ product.price }} </li>
                            {% endfor %}
                        </ul>
                </div>

            {% endfor %}
        </div>
    {% else %}
        <div>No order</div>
    {% endif %}
     <div>
        <a href="{% url 'shopapp:create_order' %}"> Create a new order </a>
    </div>
{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}
{% block title %}
    Update order
{% endblock %}

{% block body %}
    <h1>
        Update a order
    </h1>

    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Update
            </button>
        </form>
    </div>
   <div>
       <a href="{% url 'shopapp:order_details' pk=object.pk %}"> Back to order #{{ object.pk }}</a>
   </div>
{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items  %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addlink">Import CSV</a>
    </li>
    {{ block.super }}
{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>
        Create a new product
    </h1>

    <div>
        <form method="post", enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>
   <div>
        <a href="{% url 'shopapp:products_list' %}"> Products List</a>
    </div>
{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}
{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>
        Update a product
    </h1>

    <div>
        <form method="post", enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Update
            </button>
        </form>
    </div>
   <div>
       <a href="{% url 'shopapp:product_details' pk=object.pk %}"> Back to product #{{ object.pk }}</a>
   </div>
{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Product' %} {{ product.pk }}
{% endblock %}
{% block body %}
    <h1> {% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
    <div>
        <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
        <div>{% translate 'Price' %}: {{ product.price }}</div>
        <div>{% translate 'Discount' %}: {{ product.discount }}</div>
        <div>{% translate 'Archived' %}: {{ product.archived }}</div>
        <div>{% translate 'Created_by' %}: {{ product.created_by }}</div>
        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
        <h3>{% translate 'Images' %}:</h3>
            {% blocktranslate count images_count=product.images.all|length %}
                There is only one image
                {% plural %}
                There are {{ images_count }} images
            {% endblocktranslate %}
            {% for img in product.images.all %}
            <div>
                <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
            </div>

            {% endfor%}

    </div>
    {% url 'shopapp:product_update' pk=product.pk  as update %}
    {% url 'shopapp:product_archived' pk=product.pk  as archived %}
    {% url 'shopapp:products_list'  as back %}
    {% blocktranslate %}
    <div>
        <a href=" {{update}}">Update product</a>
    </div>
    <div>
        <a href=" {{archived}}">Archived product</a>
    </div>
    <div>
        <a href=" {{back}}">Back to products list</a>
    </div>
    {% endblocktranslate %}
{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products List
{% endblock %}

{% block body %}
    <h1>
        Products:
    </h1>
    {% if products %}
        <div>
            {% for product in products %}
                <div>
                    <p><a href="{% url 'shopapp:product_details' pk=product.pk %}">Name: {{ product.name }}</a></p>
                    <p>Price: {{ product.price }}</p>
                    <p>Discount: {% firstof product.discount 'no discount' %}</p>

                    {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endif %}

   <div>
        {% if perms.shopapp.add_product %}
            <a href="{% url 'shopapp:create_product' %}"> Create a new product</a>
        {% endif %}
    </div>

{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% block title %}
    Shop Index
{% endblock %}
{% block body %}
    <h1>
        Shop Index
    </h1>
    <div>
        <h2>
            List Urls:
        </h2>
        <ul>
            {% for url in urls %}
                <li>
                   <a href={{url}} target="_blank"> {{ url }} </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div>
         {% lorem 3 p random %}
     </div>
{% endblock %}

M_18_Django_Cache/mysite/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Order List
{% endblock %}

{% block body %}
{% if request.user.is_authenticated %}
        <div>
            <h2>Info User</h2>
            <p>Username: {{ owner.username}}</p>
            <p>First name: {{ owner.first_name}}</p>
            <p>Last name: {{ owner.last_name}}</p>
            <p>Email: {{ owner.email}}</p>
            <p>Bio: {{ owner.profile.bio }}</p>
        </div>
        {% if object_list %}
            <h2>Пользователь {{ owner.username }} выполнил следующие заказы:</h2>
            <div>
                {% cache 100 order_list owner.id %}
                {% for order in object_list %}
                    <div>
                        <p>Order #{{order.pk}}</p>
                        <p>Order by: {% firstof order.user.first_name order.user.username %}</p>
                        <p>Delivery_address: {{ order.delivery_address }}</p>
                        <p>Promocode: {{ order.promocode }}</p>
                    </div>
                    <div>
                        Products in order
                        <ul>
                            {% for product in order.products.all %}
                            <li> {{ product.name }} for $ {{ product.price }} </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <br>
                {% endfor %}
                {% endcache %}
            </div>
        {% else %}
        <div>У пользователя {{ owner.username }} ещё нет заказов</div>
        {% endif %}

{% else %}
    <p>User is anonymous</p>
{% endif %}
{% endblock %}