M_18_Django_Cache/mysite/myauth/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView


from .views import \
    get_cookie_view, \
    set_cookie_view, \
    get_session_view, \
    set_session_view, \
    MyLogoutView, \
    RegisterView, \
    AboutMe, \
    AvatarUpdateView, \
    ProfileListView, \
    ProfileDetailsView, \
    ProfileRegisterView, \
    ProfileDeleteView, \
    update_profile

app_name = 'accounts'


urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("profiles/", ProfileListView.as_view(), name="profile_list"),
    path("profiles/create/", ProfileRegisterView.as_view(), name="profile_create"),
    path("profiles/<int:pk>/", ProfileDetailsView.as_view(), name="profile_detail"),
    path("about-me/", AboutMe.as_view(), name="about-me"),
    path("profiles/update_profile/", update_profile, name="profile_update"),
    path("profiles/avatar/<int:pk>/update/", AvatarUpdateView.as_view(), name="avatar_update"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/<int:pk>/delete/", ProfileDeleteView.as_view(), name="profile_delete"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
]

M_18_Django_Cache/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from django.conf.urls.i18n import i18n_patterns
from .sitemaps import sitemaps

urlpatterns = [
    # path('', include('shopapp.urls')),
    # path('shop/', include('shopapp.urls')),
    # path('admin/doc/', include('django.contrib.admindocs.url')),
    # path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('blogapp/', include('blogapp.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",)

]

urlpatterns += i18n_patterns(
    path('', include('shopapp.urls')),
    path('shop/', include('shopapp.urls')),
    path('api/schema', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

M_18_Django_Cache/mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


def profile_avatar_directory_path(instance: "Profile", filename: str) -> str:
    return f"profile/user_{instance.user_id}/avatar/{filename}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(
        null=True, blank=True,
        upload_to=profile_avatar_directory_path,
        )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.avatar:
            img = Image.open(self.avatar.path)
            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.avatar.path)

M_18_Django_Cache/mysite/myauth/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'email'


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = 'bio',

M_18_Django_Cache/mysite/myauth/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView, DetailView, ListView, DeleteView
from django.contrib.auth.forms import UserCreationForm

from .models import Profile
from .forms import UserForm, ProfileForm
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('accounts:login')


class AboutMe(TemplateView):
    template_name = "myauth/about-me.html"


class ProfileListView(ListView):
    queryset = (
        Profile.objects.select_related("user")
    )


class ProfileDetailsView(DetailView):
    queryset = (
        Profile.objects.select_related("user")
    )


class AvatarUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user.is_staff\
                or self.request.user.profile.pk == self.get_object().pk:
            return True
        else:
            return False

    model = Profile
    fields = "avatar",
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "accounts:profile_detail",
            kwargs={"pk": self.object.pk}
        )


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("accounts:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        # Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class ProfileRegisterView(CreateView):
    model = Profile
    fields = "bio", "avatar",
    success_url = reverse_lazy("accounts:about-me")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProfileDeleteView(UserPassesTestMixin, DeleteView):

    def test_func(self):
        return self.request.user.is_superuser

    model = Profile
    success_url = reverse_lazy("accounts:profile_list")


def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r}")


def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")


def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:about-me')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'myauth/update.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

M_18_Django_Cache/mysite/myauth/templates/myauth/about-me.html
{% extends "myauth/base.html" %}

{% block tittle %}
  About Me
{% endblock %}

{% block body %}
  <h1>User Info</h1>
  {% if user.is_authenticated %}
    {% if user.profile.pk %}
      {% if user.profile.avatar %}
        <div><img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}"></div>
      {% else %}
        <div>
          <p>Not avatar</p>
        </div>
      {% endif %}
      <div>
        <a href=" {% url 'accounts:avatar_update' pk=user.profile.pk %}">Update avatar</a>
      </div>
      <div>
        <h2>Detail</h2>
          <p>Username: {{ user.username}}</p>
          <p>First name: {{ user.first_name}}</p>
          <p>Last name: {{ user.last_name}}</p>
          <p>Email: {{ user.email}}</p>
          <p>Bio: {{ user.profile.bio }}</p>
      </div>
      <div>
        <a href=" {% url 'accounts:profile_update' %}">Update profile</a>
      </div>
    {% else %}
      <div>
        <h2> User not profile </h2>
          <p><a href="{% url 'accounts:profile_create' %}"> Create a profile </a></p>
          <p></p>
      </div>
    {% endif %}
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
  <div>
    <p></p>
    <p><a href=" {% url 'accounts:profile_list' %}">Back to profiles list</a></p>
  </div>
{% endblock %}

M_18_Django_Cache/mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base body
    {% endblock%}
</body>
</html>

M_18_Django_Cache/mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

M_18_Django_Cache/mysite/myauth/templates/myauth/profile_confirm_delete.html
{% extends "myauth/base.html" %}

{% block title %}
    Delete Profile {{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete profile {{ object.pk }}?</h1>
    <br>
    <div>
        <a href="{% url 'accounts:profile_detail' pk=object.pk %}">Back to profile</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token%}
            {{ form.as_p}}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

M_18_Django_Cache/mysite/myauth/templates/myauth/profile_detail.html
{% extends "myauth/base.html" %}

{% block tittle %}
  Profile
{% endblock %}

{% block body %}
  <h1>Profile # {{object.pk}}  </h1>
    <div>
        <div>
            {% if object.avatar %}
              <img src="{{ object.avatar.url }}" alt="{{ object.avatar.name }}">
            {% else %}
            <p>Not avatar</p>
            {% endif %}
        </div>
        <div>
            {% if user.is_staff or user.profile.pk == object.user.profile.pk %}
                <a href=" {% url 'accounts:avatar_update' pk=object.pk %}">Update avatar</a></p>
            {% endif %}
        </div>
        <p>Username: {{ object.user.username }}</p>
        <p>First name: {{ object.user.first_name}}</p>
        <p>Last name: {{ object.user.last_name}}</p>
        <p>Email: {{ object.user.email}}</p>
        <p>Bio: {{ object.user.profile.bio }}</p>
    </div>
    <div>
        {% if user.is_superuser %}
            <p><a href=" {% url 'accounts:profile_delete' pk=object.pk %}">Delete profile</a></p>
        {% endif %}
        <p><a href=" {% url 'accounts:profile_list' %}">Back to profiles list</a></p>
    </div>
{% endblock %}

M_18_Django_Cache/mysite/myauth/templates/myauth/profile_form.html
{% extends "myauth/base.html" %}

{% block title %}
    Create profile
{% endblock %}

{% block body %}
    <h1>
        Create a new profile
    </h1>

    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Create
            </button>
        </form>
    </div>
   <div>
        <a href="{% url 'accounts:about-me' %}"> About Me</a>
    </div>
{% endblock %}

M_18_Django_Cache/mysite/myauth/templates/myauth/profile_list.html
{% extends "myauth/base.html" %}

{% block tittle %}
  Profile List
{% endblock %}

{% block body %}
  <h1>Profiles</h1>
  {% if object_list %}
    <div>
      {% for profile in object_list %}
        <div>
          <p><a href="{% url 'accounts:profile_detail' pk=profile.pk %}">User: {{ profile.user.username }}</a></p>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <div>No profile</div>
  {% endif %}
{% endblock %}

M_18_Django_Cache/mysite/myauth/templates/myauth/profile_update_form.html
{% extends "myauth/base.html" %}

{% block tittle %}
  Update avatar
{% endblock %}

{% block body %}
  <h1> Update an avatar </h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Update
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'accounts:profile_detail' pk=object.pk %}"> Back to profile </a>
    </div>

{% endblock %}

M_18_Django_Cache/mysite/myauth/templates/myauth/register.html
{% extends "myauth/base.html" %}

{% block title %}
  Register
{% endblock %}

{% block body %}
    <h1> Register </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

M_18_Django_Cache/mysite/myauth/templates/myauth/update.html
{% extends "myauth/base.html" %}

{% block title %}
    Update profile
{% endblock %}

{% block body %}
    <h1>
        Update profile
    </h1>
        <div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <button type="submit">Update profile</button>
            </form>
        </div>
   <div>
        <a href="{% url 'accounts:about-me' %}"> About Me </a>
   </div>
{% endblock %}